theme: jekyll-theme-architect

title: [glassfish-maven-plugin-legacy]
description: [Maven2 plugin for GlassFish users]

# sidebar links url
links:
  source: https://github.com/javaee/glassfish-maven-plugin-legacy
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

